-- AlterTable
ALTER TABLE "SiteAppearance" ADD COLUMN "lgOpacity" INTEGER NOT NULL DEFAULT 12;
ALTER TABLE "SiteAppearance" ADD COLUMN "lgBlur" INTEGER NOT NULL DEFAULT 24;
ALTER TABLE "SiteAppearance" ADD COLUMN "lgSaturation" INTEGER NOT NULL DEFAULT 120;
ALTER TABLE "SiteAppearance" ADD COLUMN "lgBrightness" INTEGER NOT NULL DEFAULT 110;
ALTER TABLE "SiteAppearance" ADD COLUMN "lgEdgeHighlight" INTEGER NOT NULL DEFAULT 25;
ALTER TABLE "SiteAppearance" ADD COLUMN "lgEdgeHighlightBottom" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "SiteAppearance" ADD COLUMN "lgInnerGlow" INTEGER NOT NULL DEFAULT 15;
ALTER TABLE "SiteAppearance" ADD COLUMN "lgInsetShadow" INTEGER NOT NULL DEFAULT 20;
